AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB table for AWS inventory

Resources:
  InventoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: aws-company-inventory
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: resource_type
          AttributeType: S
        - AttributeName: department
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: resource-type-index
          Keys:
            - AttributeName: resource_type
              KeyType: HASH
            - AttributeName: sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        - IndexName: department-index
          Keys:
            - AttributeName: department
              KeyType: HASH
            - AttributeName: sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10