# Bandit configuration
tests:
  - B201  # flask_debug_true
  - B301  # pickle
  - B302  # marshal
  - B303  # md5
  - B304  # des
  - B305  # cipher
  - B306  # mktemp_q
  - B307  # eval
  - B308  # mark_safe
  - B309  # httpsconnection
  - B310  # urllib_urlopen
  - B311  # random
  - B312  # telnetlib
  - B313  # xml_bad_etree
  - B314  # xml_bad_elementtree
  - B315  # xml_bad_expatreader
  - B316  # xml_bad_expatbuilder
  - B317  # xml_bad_sax
  - B318  # xml_bad_minidom
  - B319  # xml_bad_pulldom
  - B320  # xml_bad_etree
  - B321  # ftplib
  - B322  # input
  - B323  # unverified_context
  - B324  # hashlib_new_insecure_functions
  - B325  # tempnam
  - B401  # import_telnetlib
  - B402  # import_ftplib
  - B403  # import_pickle
  - B404  # import_subprocess
  - B405  # import_xml_etree
  - B406  # import_xml_sax
  - B407  # import_xml_expat
  - B408  # import_xml_minidom
  - B409  # import_xml_pulldom
  - B410  # import_lxml
  - B411  # import_xmlrpclib
  - B412  # import_httpoxy
  - B413  # import_pycrypto
  - B501  # request_with_no_cert_validation
  - B502  # ssl_with_bad_version
  - B503  # ssl_with_bad_defaults
  - B504  # ssl_with_no_version
  - B505  # weak_cryptographic_key
  - B506  # yaml_load
  - B507  # ssh_no_host_key_verification
  - B601  # paramiko_calls
  - B602  # subprocess_popen_with_shell_equals_true
  - B603  # subprocess_without_shell_equals_true
  - B604  # any_other_function_with_shell_equals_true
  - B605  # start_process_with_a_shell
  - B606  # start_process_with_no_shell
  - B607  # start_process_with_partial_path
  - B608  # hardcoded_sql_expressions
  - B609  # linux_commands_wildcard_injection

skips:
  - B404  # Allow subprocess import (needed for legitimate use)
  - B603  # Allow subprocess without shell (safe when used properly)

exclude_dirs:
  - /tests/
  - /venv/
  - /.tox/
  - /build/
  - /dist/

profiles:
  all:
    include:
      - any_other_function_with_shell_equals_true
      - assert_used
      - exec_used
      - hardcoded_bind_all_interfaces
      - hardcoded_password_string
      - hardcoded_password_funcarg
      - hardcoded_password_default
      - hardcoded_sql_expressions
      - hardcoded_tmp_directory
      - hashlib_new_insecure_functions
      - linux_commands_wildcard_injection
      - paramiko_calls
      - password_config_option_not_marked_secret
      - request_with_no_cert_validation
      - set_bad_file_permissions
      - ssl_with_bad_defaults
      - ssl_with_bad_version
      - ssl_with_no_version
      - start_process_with_a_shell
      - start_process_with_no_shell
      - start_process_with_partial_path
      - subprocess_popen_with_shell_equals_true
      - subprocess_without_shell_equals_true
      - try_except_continue
      - try_except_pass
      - unverified_context
      - use_of_mako_templates
      - weak_cryptographic_key
      - yaml_load