# Ruff configuration file
line-length = 120
target-version = "py311"

[lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "ARG", # flake8-unused-arguments
    "SIM", # flake8-simplify
    "S",   # flake8-bandit
    "T20", # flake8-print
    "PT",  # flake8-pytest-style
    "RET", # flake8-return
    "LOG", # flake8-logging
    "G",   # flake8-logging-format
    "INP", # flake8-no-pep420
    "PIE", # flake8-pie
]

ignore = [
    "E501",  # Line too long (handled by formatter)
    "S101",  # Use of assert detected
    "S104",  # Possible binding to all interfaces
]

[lint.per-file-ignores]
"tests/*" = ["S101", "S106"]  # Allow asserts and hardcoded passwords in tests
"scripts/*" = ["T20"]  # Allow print statements in scripts

[lint.isort]
known-first-party = ["aws_inventory"]
force-single-line = true

[lint.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.Query"]

[lint.pyupgrade]
keep-runtime-typing = true

[format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true