name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Ruff
        run: ruff .
      - name: Mypy
        run: mypy src || true
      - name: Bandit
        run: bandit -r src -c pyproject.toml
      - name: Pytest
        run: pytest -m "not aws"

  deploy-test:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-azure-cli@v1
      - name: Build Bicep
        run: az bicep build --file infrastructure/function_app_appsvc.bicep
      - name: What-if Deployment
        run: az deployment sub create --location eastus --template-file infrastructure/function_app_appsvc.bicep --what-if

